name: vaden_hostinger
description: Projeto de test.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

dependencies:
  vaden_security: ^0.0.4
  vaden: ^0.0.12

dev_dependencies:
  build_runner: ^2.4.14
  vaden_class_scanner: ^0.0.12